# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: drydocker 0.1.5 ruby lib

Gem::Specification.new do |s|
  s.name = "drydocker"
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kevin Littlejohn"]
  s.date = "2015-01-13"
  s.description = "Run tests on change in a docker container continuously"
  s.email = "kevin@littlejohn.id.au"
  s.executables = ["drydocker"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rubocop.yml",
    "Dockerfile",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/drydocker",
    "drydocker.gemspec",
    "lib/drydocker.rb",
    "spec/drydocker_spec.rb",
    "spec/spec_helper.rb",
    "test/helper.rb",
    "test/test_loop_test.rb",
    "wercker.yml"
  ]
  s.homepage = "http://github.com/silarsis/drydocker"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Test something in a loop, in a docker container"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<listen>, ["~> 2.8"])
      s.add_runtime_dependency(%q<ptools>, ["~> 1.3"])
      s.add_development_dependency(%q<shoulda>, ["~> 3.5"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.9"])
      s.add_development_dependency(%q<rspec>, ["~> 3.1"])
      s.add_development_dependency(%q<fuubar>, ["~> 2.0"])
    else
      s.add_dependency(%q<listen>, ["~> 2.8"])
      s.add_dependency(%q<ptools>, ["~> 1.3"])
      s.add_dependency(%q<shoulda>, ["~> 3.5"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<simplecov>, ["~> 0.9"])
      s.add_dependency(%q<rspec>, ["~> 3.1"])
      s.add_dependency(%q<fuubar>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<listen>, ["~> 2.8"])
    s.add_dependency(%q<ptools>, ["~> 1.3"])
    s.add_dependency(%q<shoulda>, ["~> 3.5"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<simplecov>, ["~> 0.9"])
    s.add_dependency(%q<rspec>, ["~> 3.1"])
    s.add_dependency(%q<fuubar>, ["~> 2.0"])
  end
end

