# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: drydocker 0.1.11 ruby lib

$LOAD_PATH << File.expand_path("../lib", __FILE__)
require "drydocker"

Gem::Specification.new do |gem|
  gem.name = "drydocker"
  gem.version = Drydocker::VERSION
  gem.date = Date.today.to_s

  gem.require_paths = ["lib"]
  gem.authors = ["Kevin Littlejohn"]
  gem.email = "kevin@littlejohn.id.au"
  gem.executables = ["drydocker"]
  gem.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  gem.files = Dir.glob("{bin,lib}/**/*") + %w(README.md LICENSE.txt)
  gem.homepage = "http://github.com/silarsis/drydocker"
  gem.licenses = ["MIT"]
  gem.summary = "Test something in a loop, in a docker container"
  gem.description = "Run tests on change in a docker container continuously"

  gem.add_runtime_dependency("listen", ["~> 2.8"])
  gem.add_runtime_dependency("ptools", ["~> 1.3"])
  gem.add_development_dependency("codeclimate-test-reporter", ["~> 0.4"])
  gem.add_development_dependency("shoulda", ["~> 3.5"])
  gem.add_development_dependency("rdoc", ["~> 3.12"])
  gem.add_development_dependency("bundler", ["~> 1.0"])
  gem.add_development_dependency("simplecov", ["~> 0.9"])
  gem.add_development_dependency("rspec", ["~> 3.1"])
  gem.add_development_dependency("fuubar", ["~> 2.0"])
  gem.add_development_dependency("rake", ["~> 10.4"])
end
